//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPractica04
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonos
    {
        public int AbonoID { get; set; }
        public Nullable<int> PrincipalID { get; set; }
        public string Compra { get; set; }
        public Nullable<decimal> Abono { get; set; }
        public Nullable<decimal> SaldoAnterior { get; set; }
        public Nullable<System.DateTime> FechaAbono { get; set; }
    
        public virtual Principal Principal { get; set; }
    }
}
